FROM nginx:latest

ARG ENVIRONMENT

RUN apt-get update \
    && apt-get install -y git npm\
    && rm -rf /var/lib/apt/lists/* 
# needs a npm i, and change dir to website dir
EXPOSE 8080

RUN git clone https://github.com/olilinvar/weBallin/.git \

WORKDIR /WeBallin/website/frontend/

RUN npm i

# COPY code_to_copy/ /where_to_copy_it/


# Shit to run essentially to start the container
CMD ["frontend"]