# Use an official MongoDB runtime as a parent image
FROM mongo:latest

# Set environment variables (replace 'yourpassword' with your desired password)
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=yourpassword

# Add a database script
COPY mongo-init.js /docker-entrypoint-initdb.d/

# Make port 27017 available to the world outside this container
EXPOSE 27017

# Run mongod when the container launches
CMD ["mongod"]

#bingaied gaming