version: '3'
services:
  backend:
    container_name: backend
    build:
      dockerfile: dockerfile.backend
    ports:
      - "8080:7175"
    networks:
      - frontback-network
      - database-network

  frontend:
    container_name: frontend
    build:
      dockerfile: dockerfile.frontend
    networks:
      - frontback-network

  mongo: # Might have to be called mongo
    image: mongo:latest
    container_name: heltmongo
    environment:  # SETS SUPER USERS FOR THE ENTIRE DATABASE
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpass # MONGODB_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb-root-pw
    ports:
      - "27017:27017"
    networks:
      - database-network
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-data:/data/db

  mongo-manager:
    image: mongo-express:latest
    container_name: mongo-manager
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=mongo  
      - ME_CONFIG_BASICAUTH_USERNAME=username
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=adminpass
    networks:
      - database-network
    volumes:
      - mongodb-data

volumes:
  mongodb-data:

networks:
  database-network:
    driver: bridge
  frontback-network:
    driver: bridge

# Mongo vs trad consepts

#MongoDB          Traditional SQL
#Database         Database
#Collection       Table
#Document         Row
#$lookup          Join
#Index            Index
#ACID Transaction ACID transaction
#Single Machine   Multiple Nodes


# NOTHING IS WORKING?, WELL BELOV IS SECRET OPTION IF ALL HOPE IS ERADICATED
#services:
#mongodb:
#image: mongo
#container_name: mongodb
#environment:
#- MONGO_INITDB_ROOT_USERNAME=root
#- MONGO_INITDB_ROOT_PASSWORD=pass12345
#volumes:
#- mongodb-data:/data/db
#networks:
#- mongodb_network
#ports:
#- 27017:27017
#healthcheck:
#test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
#interval: 30s
#timeout: 10s
#retries: 3
#restart: unless-stopped
#mongo-express:
#image: mongo-express
#container_name: mongo-express
#environment:
#- ME_CONFIG_MONGODB_SERVER=mongodb
#- ME_CONFIG_MONGODB_ENABLE_ADMIN=true
#- ME_CONFIG_MONGODB_ADMINUSERNAME=root
#- ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
#- ME_CONFIG_BASICAUTH_USERNAME=admin
#- ME_CONFIG_BASICAUTH_PASSWORD=admin123
#volumes:
#- mongodb-data
#depends_on:
#- mongodb
#networks:
#- mongodb_network
#ports:
#- 8081:8081
#healthcheck:
#test:  wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1
#interval: 30s
#timeout: 10s
#retries: 3
#restart: unless-stopped
#volumes:
#mongodb-data:
#name: mongodb-data
#networks:
#mongodb_network:
#name: mongodb_network