version: '3'
services:
  backend:
    build:
      dockerfile: dockerfile.backend
    ports:
      - "8080:7175"
    networks:
      - container-network

#  frontend:
#    build:
#      context: .
#      dockerfile: dockerfile.frontend
#    networks:
#      - container_network

  database:
    image: mongo:latest
    #hostname: mongo
    container_name: heltmongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=changeme # MONGODB_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb-root-pw
    ports:
      - "27017:27017"
    networks:
      - container-network
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:

networks:
  container-network:
    driver: bridge


#MongoDB          Traditional SQL
#Database         Database
#Collection       Table
#Document         Row
#$lookup          Join
#Index            Index
#ACID Transaction ACID transaction
#Single Machine   Multiple Nodes