FROM nginx:latest

LABEL maintainer="dont@contact.please"

#ARG APP_LOCATION=/usr/src/frontend

RUN apt-get update \
    && apt-get install -y git npm\
    && rm -rf /var/lib/apt/lists/* 

#WORKDIR ${APP_LOCATION}

RUN git clone https://github.com/olilinvar/weBallin/.git \

WORKDIR /WeBallin/website/frontend/

RUN npm i

EXPOSE 8080
# Shit to run essentially to start the container
#CMD ["frontend"]