version: '3'
services:
  backend:
    container_name: backend
    build:
      dockerfile: dockerfile.backend
    ports:
      - "8080:7175"
    networks:
      - frontback-network
      - database-network

  frontend:
    container_name: frontend
    build:
      dockerfile: dockerfile.frontend
    networks:
      - frontback-network

  database:
    image: mongo:latest
    container_name: heltmongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=changeme # MONGODB_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb-root-pw
    ports:
      - "27017:27017"
    networks:
      - database-network
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:

networks:
  database-network:
    driver: bridge
  frontback-network:
    driver: bridge

# Mongo vs trad consepts

#MongoDB          Traditional SQL
#Database         Database
#Collection       Table
#Document         Row
#$lookup          Join
#Index            Index
#ACID Transaction ACID transaction
#Single Machine   Multiple Nodes